#!/bin/sh

setxkbmap -model abnt2 -layout br -variant abnt2

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x pipewire > /dev/null || pipewire &
pgrep -x picom > /dev/null || picom -b --config ~/.config/picom/picom.conf &
pgrep -x dunst > /dev/null || dunst &

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

is_hdmi_connected() {
    for card in /sys/class/drm/card*; do
        for hdmi in "$card"/*HDMI*/status; do
            [ -f "$hdmi" ] || continue
            read -r status < "$hdmi"
            [ "$status" = "connected" ] && return 0
        done
    done
    return 1
}

if is_hdmi_connected; then
    bspc monitor HDMI-1 -d 0 1 2 3 4
    bspc monitor eDP-1 -d 5 6 7 8 9
else
    bspc monitor eDP-1 -d 0 1 2 3 4 5 6 7 8 9
fi

bspc rule -a Dunst layer=above manage=off border=off
bspc rule -a "*:*:Picture-in-Picture" state=floating sticky=on

xsetroot -cursor_name left_ptr

