#!/bin/sh

AUTOLOAD="$(pwd)/scripts"

source $AUTOLOAD/sxhkd
source $AUTOLOAD/abnt2

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc monitor HDMI-A-0 -d 0 1 2 3
bspc monitor eDP -d 4 5

